### ISSUE TITLE
App Crashes When Rotation on NumbersStoragePublisherFragment

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#17]
## Steps to Reproduce

1. Enter `NumbersStoragePublisherFragment`.
1. Enter the login form.
1. Rotate the screen.
1. APP crashes.

## Logs

``` txt
Caused by java.lang.IllegalStateException: rootLayout must not be null
       at io.numbersprotocol.starlingcapture.BaseActivity.disableLayoutFullScreen(BaseActivity.kt:29)
       at io.numbersprotocol.starlingcapture.publisher.numbers_storage.NumbersStoragePublisherFragment.onAttach(NumbersStoragePublisherFragment.kt:24)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1707)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
       at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:206)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:135)
       at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
       at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
       at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
       at io.numbersprotocol.starlingcapture.databinding.ActivityBaseBinding.inflate(ActivityBaseBinding.java:62)
       at io.numbersprotocol.starlingcapture.databinding.ActivityBaseBinding.inflate(ActivityBaseBinding.java:48)
       at io.numbersprotocol.starlingcapture.BaseActivity.onCreate(BaseActivity.kt:15)
       at android.app.Activity.performCreate(Activity.java:7155)
       at android.app.Activity.performCreate(Activity.java:7146)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1289)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3011)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3166)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5090)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4999)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:7124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
```

**Comment by scott-dt** [comment]
take picture video , Rotation <-  pass
go to set page , rotation <- pass
