### ISSUE TITLE
Crash When Rotate on The Bottom Dialog Opened

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#43]
## Related Crashlytics Report

One of the reports can be found [here](https://console.firebase.google.com/u/3/project/starling-capture/crashlytics/app/android:io.numbersprotocol.starlingcapture.numbers.debug/issues/48bdfab8b00c69a719acd362e403ab77?time=last-seven-days&sessionId=5F3DE110006D00014A3C8267C7AA26E3_DNE_0_v2).

## Error Logs

``` txt
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@2968373[BaseActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:394)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:375)
       at android.app.Dialog.dismiss(Dialog.java:358)
       at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.kt:400)
       at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:133)
       at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:46)
       at com.afollestad.materialdialogs.bottomsheets.UtilKt$setCallbacks$1.onStateChanged(Util.kt:59)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1092)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1517)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
       at android.view.Choreographer.doCallbacks(Choreographer.java:767)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:7124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
```

## Root Cause

This is caused by the upstream issues: https://github.com/afollestad/material-dialogs/issues/1825, https://github.com/afollestad/material-dialogs/issues/1946 and https://github.com/afollestad/material-dialogs/issues/1990.

**Comment by seanwu1105** [comment]
@tammyyang The upstream issues have not been fixed at this time. Thus, I think we should postpone this one to next sprint.

**Comment by seanwu1105** [comment]
Move the description by @scott-dt.

==

## Description

 當手機開啟自動旋轉將手機打橫90度開啟相機，會造成 crash

## Steps to Reproduce

1. 開啟app 並將手機轉90度
2. 點擊 "+" 選取"Built-in camera"
3. 會跳出 「Starling Capture 」已停止運作

## Expected Behavior

* Expected: 相機可正常開啟運行
* Actual: 會跳出 「Starling Capture 」已停止運作 並跳出app

## Logs

![Screenshot_20200923-124200](https://user-images.githubusercontent.com/62582260/93970514-d813ea80-fda0-11ea-8f55-89dcd235a101.png)

## Environment

* Version: 1.6.0
* OS: Android 8.1
* Device: HTC Exodus 1s

**Comment by seanwu1105** [comment]
Replace [the bottom sheet dialog from material-dialogs library](https://github.com/afollestad/material-dialogs/blob/main/documentation/BOTTOMSHEETS.md) with [the simple dialog from Material Component](https://material.io/develop/android/components/dialogs#simple-dialog) to avoid the issue.
